# Generated by Django 3.0.5 on 2020-05-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='savedproduct',
            constraint=models.UniqueConstraint(fields=('user', 'sub_product'), name='each_product_saved_only_once'),
        ),
    ]
