# Generated by Django 3.0.5 on 2020-04-28 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=368)),
                ('image', models.URLField(max_length=368)),
                ('nutriscore', models.CharField(max_length=1)),
                ('fat', models.DecimalField(decimal_places=4, max_digits=7)),
                ('saturated_fat', models.DecimalField(decimal_places=4, max_digits=7)),
                ('sugar', models.DecimalField(decimal_places=4, max_digits=7)),
                ('salt', models.DecimalField(decimal_places=4, max_digits=7)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_savedproducts', to='products.Product')),
                ('replaced_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced_savedproducts', to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
